name: flutter_breakpoints
description: "A Flutter package for responsive design using customizable breakpoints."
topics:
  - flutter
  - responsive-design
  - breakpoints
  - customizable
version: 1.0.0
homepage: none

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/demo.gif
